version: '1'
services:
  database:
    image: mariadb:10.6
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - './database:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    ports:
      - 8282:80
    environment:
      PMA_PASSWORD: password
      PMA_USER: root
      PMA_HOSTS: database
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile.develop # for development
    container_name: my-blog-api
    working_dir: /app
    volumes:
      - './:/app'
    ports:
      - 8080:8080
    depends_on:
      - database
    links:
      - database
    restart: always
